services:
  web:
    build: ./php
    ports:
      - "6644:80"
    env_file:
      - .env
    volumes:
      - "./php/:/var/www/html"
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "9335:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  tomcat:
    image: tomcat:9.0
    env_file:
      - .env
    ports:
      - "7788:8080"
      - "8001:8000"
    environment:
      JPDA_ADDRESS: "*:8000"
      JPDA_TRANSPORT: "dt_socket"
    volumes:
      - ./java/Proyecto_Grupo3/target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
    command: ["catalina.sh", "jpda", "run"]

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-app
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Europe/Madrid
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  postgres_data:
  n8n_data:

networks:
  proxy:
    external: true
    name: npm
