services:
  flaskapp:
    image: python:3.12-slim-bookworm
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8383:8888"
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    restart: unless-stopped


  db-users:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "9336:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

volumes:
  postgres_data:

